config/routes.rb
Rails.application.routes.draw do
  root :to => "site#root"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :group_memberships, only: [:create, :destroy]
  resources :event_reservations, only: [:create, :destroy]
  resources :interestings, only: [:create, :destroy]

  namespace :api, :defaults => { :format => :json } do
    resources :groups, except: [:new, :edit]
    resources :events, except: [:new, :edit]
    resources :interests, only: [:index, :show]
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id             :integer          not null, primary key
#  organizer_id   :integer          not null
#  title          :string           not null
#  description    :text             not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  filepicker_url :string
#

class Group < ActiveRecord::Base
  validates :organizer_id, :title, :description, presence: true

  belongs_to :organizer, class_name: "User"
  has_many :events
  has_many :memberships, class_name: "GroupMembership"
  has_many :members, through: :memberships, source: :member
  has_many :interestings, as: :interestable
  has_many :interests, through: :interestings, source: :interest
end

app/controllers/api/groups_controller.rb
class Api::GroupsController < ApplicationController
  before_action :require_signed_in
  before_action :group_require_current_user, only: [:update, :destroy]

  def index
    type = params["type"]
    if type == "created"
      @groups = Group.where(organizer_id: current_user.id)
    elsif type == "joined"
      @groups = current_user.groups_joined
    elsif type == "other"
      @groups = Group.where.not(
        organizer_id: current_user.id,
        id: current_user.groups_joined.map(&:id)
      )
    end

    if params["interest_id"].to_i > 0
      @groups = @groups.includes(:interests).where(interests: { id: params["interest_id"].to_i })
    end

    render :json => @groups
  end

  def create
    @group = Group.new(group_params)
    @group.organizer_id = current_user.id

    if @group.save
      render :json => @group
    else
      @errors = @group.errors.full_messages
      render "form", :status => :unprocessable_entity
    end
  end

  def show
    @group = Group.find(params[:id])
    @events = @group.events
    @organizer = @group.organizer
    @owned = { owned: (@group.organizer == current_user) }
    @interests = @group.interests

    membership = GroupMembership.where(member_id: current_user.id, group_id: params[:id])
    if membership[0]
      @membership_id = { membership_id: membership[0].id }
    else
      @membership_id = { membership_id: 0 }
    end

    @joined = { joined: (current_user.groups_joined.exists?(@group.id)) }
    render "show"
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      render :json => @group
    else
      @errors = @group.errors.full_messages
      render "form", :status => :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    render :json => @group
  end

  private

  def group_params
    params.require(:group).permit(:title, :description, :filepicker_url)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_signed_in

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.organizer_id = current_user.id

    if @group.save
      redirect_to @group
    else
      flash.now[:errors] = @group.errors.full_messages
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
    redirect_to @group unless @group.organizer_id == current_user.id
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      flash.now[:errors] = @group.errors.full_messages
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h3>Edit Group:</h3>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>

<form action="/groups/<%= @group.id %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="hidden"
    name="_method"
    value="patch">

  <div>
    <input
      type="text"
      name="group[title]"
      placeholder="Title"
      value="<%= @group.title %>">
  </div>

  <div>
    <textarea name="group[description]"
      rows="8" cols="40"
      placeholder="Description"><%= @group.description %></textarea>
  </div>

  <input type="submit" value="Update!">
</form>

app/views/groups/new.html.erb
<h3>New Group:</h3>

<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>

<form action="/groups" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <div>
    <input
      type="text"
      name="group[title]"
      placeholder="Title"
      value="<%= @group.title %>">
  </div>

  <div>
    <textarea name="group[description]"
      rows="8" cols="40"
      placeholder="Description"><%= @group.description %></textarea>
  </div>

  <input type="submit" value="Create!">
</form>

app/views/groups/show.html.erb
<h3><%= @group.title %></h3>

<div>
  Created by:
  <a href="/users/<%= @group.organizer.id %>">
    <%= @group.organizer.username %>
  </a>
</div>

<div>
  <%= @group.description %>
</div>

<div>
  <%= button_to "Edit", edit_group_url(@group), method: :get %>
</div>

<div>
  <%= button_to "Destroy!", @group, method: :delete %>
</div>

<div>
  <a href="/groups">All Groups</a>
</div>