config/routes.rb
Rails.application.routes.draw do
  root :to => "site#root"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :group_memberships, only: [:create, :destroy]
  resources :event_reservations, only: [:create, :destroy]
  resources :interestings, only: [:create, :destroy]

  namespace :api, :defaults => { :format => :json } do
    resources :groups, except: [:new, :edit]
    resources :events, except: [:new, :edit]
    resources :interests, only: [:index, :show]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  attr_reader :password

  has_many :groups_organized, class_name: "Group", foreign_key: :organizer_id
  has_many :events_organized, through: :groups_organized, source: :events
  has_many :group_memberships, foreign_key: :member_id
  has_many :groups_joined, through: :group_memberships, source: :group
  has_many :event_reservations, foreign_key: :reserver_id
  has_many :events_reserved, through: :event_reservations, source: :event
  has_many :interestings, as: :interestable
  has_many :interests, through: :interestings, source: :interest

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user

    return user if user.is_password?(password)
    return nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save
    self.session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to "#/interests/user"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :image_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="enter-background">
  <div class="col-md-4 enter-info">
    <div class="enter-logo">
      <img src="/assets/PickUp-logo.png"/>
    </div>

    <div class="enter-description">
      <strong>Organize and Attend Pick Up Games in your Community</strong>
    </div>
  </div>

  <div class="new-user col-md-3 col-md-offset-3 enter-form">
    <h3 class="enter-header">Sign up</h3>

    <% if flash[:errors] %>
      <div class ="form-alert alert alert-danger">
        <ul>
          <% flash[:errors].each do |err| %>
            <li><%= err %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <form action="/users" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <div class="form-group">
        <input
          type="text"
          name="user[username]"
          class="form-control"
          placeholder="Enter username"
          value="<%= @user.username %>">
      </div>

      <div class="form-group">
        <input
          type="password"
          name="user[password]"
          class="form-control"
          placeholder="Enter password">
      </div>

      <div>
        <label>Upload An Avatar (optional):
          <br>
          <input class="btn btn-primary" type="filepicker" name="user[image_url]">
        </label>
      </div>

      <br>

      <button type="submit" class="btn btn-danger btn-enter">Sign up</button>
    </form>

    <hr>

    <h5 class="enter-subheader">Already have an account?</h5>
    <form action="<%= new_session_url %>" method="get">
      <button type="submit" class="btn btn-primary btn-enter">Log in</button>
    </form>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>